/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSalesCustomersRouteImport } from './routes/_authenticated/sales.customers'
import { Route as AuthenticatedProcurementSuppliersRouteImport } from './routes/_authenticated/procurement.suppliers'
import { Route as AuthenticatedMasterProductsRouteImport } from './routes/_authenticated/master.products'
import { Route as AuthenticatedDashboardManajemenRouteImport } from './routes/_authenticated/dashboard.manajemen'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSalesCustomersRoute =
  AuthenticatedSalesCustomersRouteImport.update({
    id: '/sales/customers',
    path: '/sales/customers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProcurementSuppliersRoute =
  AuthenticatedProcurementSuppliersRouteImport.update({
    id: '/procurement/suppliers',
    path: '/procurement/suppliers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMasterProductsRoute =
  AuthenticatedMasterProductsRouteImport.update({
    id: '/master/products',
    path: '/master/products',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardManajemenRoute =
  AuthenticatedDashboardManajemenRouteImport.update({
    id: '/dashboard/manajemen',
    path: '/dashboard/manajemen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/dashboard/manajemen': typeof AuthenticatedDashboardManajemenRoute
  '/master/products': typeof AuthenticatedMasterProductsRoute
  '/procurement/suppliers': typeof AuthenticatedProcurementSuppliersRoute
  '/sales/customers': typeof AuthenticatedSalesCustomersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/dashboard/manajemen': typeof AuthenticatedDashboardManajemenRoute
  '/master/products': typeof AuthenticatedMasterProductsRoute
  '/procurement/suppliers': typeof AuthenticatedProcurementSuppliersRoute
  '/sales/customers': typeof AuthenticatedSalesCustomersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/dashboard/manajemen': typeof AuthenticatedDashboardManajemenRoute
  '/_authenticated/master/products': typeof AuthenticatedMasterProductsRoute
  '/_authenticated/procurement/suppliers': typeof AuthenticatedProcurementSuppliersRoute
  '/_authenticated/sales/customers': typeof AuthenticatedSalesCustomersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin/users'
    | '/dashboard/manajemen'
    | '/master/products'
    | '/procurement/suppliers'
    | '/sales/customers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/users'
    | '/dashboard/manajemen'
    | '/master/products'
    | '/procurement/suppliers'
    | '/sales/customers'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin/users'
    | '/_authenticated/dashboard/manajemen'
    | '/_authenticated/master/products'
    | '/_authenticated/procurement/suppliers'
    | '/_authenticated/sales/customers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sales/customers': {
      id: '/_authenticated/sales/customers'
      path: '/sales/customers'
      fullPath: '/sales/customers'
      preLoaderRoute: typeof AuthenticatedSalesCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/procurement/suppliers': {
      id: '/_authenticated/procurement/suppliers'
      path: '/procurement/suppliers'
      fullPath: '/procurement/suppliers'
      preLoaderRoute: typeof AuthenticatedProcurementSuppliersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master/products': {
      id: '/_authenticated/master/products'
      path: '/master/products'
      fullPath: '/master/products'
      preLoaderRoute: typeof AuthenticatedMasterProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/manajemen': {
      id: '/_authenticated/dashboard/manajemen'
      path: '/dashboard/manajemen'
      fullPath: '/dashboard/manajemen'
      preLoaderRoute: typeof AuthenticatedDashboardManajemenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedDashboardManajemenRoute: typeof AuthenticatedDashboardManajemenRoute
  AuthenticatedMasterProductsRoute: typeof AuthenticatedMasterProductsRoute
  AuthenticatedProcurementSuppliersRoute: typeof AuthenticatedProcurementSuppliersRoute
  AuthenticatedSalesCustomersRoute: typeof AuthenticatedSalesCustomersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedDashboardManajemenRoute: AuthenticatedDashboardManajemenRoute,
  AuthenticatedMasterProductsRoute: AuthenticatedMasterProductsRoute,
  AuthenticatedProcurementSuppliersRoute:
    AuthenticatedProcurementSuppliersRoute,
  AuthenticatedSalesCustomersRoute: AuthenticatedSalesCustomersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
