ALTER TABLE public.stock_balances ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();
CREATE INDEX IF NOT EXISTS idx_lines_created_at ON public.lines (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_work_centers_created_at ON public.work_centers (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_machines_created_at ON public.machines (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_shifts_created_at ON public.shifts (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_downtime_reason_codes_created_at ON public.downtime_reason_codes (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_plants_created_at ON public.plants (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_products_created_at ON public.products (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_customers_created_at ON public.customers (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_materials_created_at ON public.materials (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_production_entries_created_at ON public.production_entries (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_downtime_records_created_at ON public.downtime_records (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_work_orders_created_at ON public.work_orders (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sales_orders_created_at ON public.sales_orders (created_at DESC);